<?php
require_once('../../lib/Lang.php');
header('Content-Type: text/javascript');
?>

var L__DEFAULT_PAGE_TITLE = "<?php echo LANG['app_name']; ?>";
var L__PACKAGE_CREATED = "<?php echo LANG['package_created']; ?>";
var L__COMPUTER_CREATED = "<?php echo LANG['computer_created']; ?>";
var L__JOBS_CREATED = "<?php echo LANG['jobs_created']; ?>";
var L__GROUP_CREATED = "<?php echo LANG['group_created']; ?>";
var L__REPORT_CREATED = "<?php echo LANG['report_created']; ?>";
var L__USER_CREATED = "<?php echo LANG['user_created']; ?>";
var L__NO_ELEMENTS_SELECTED = "<?php echo LANG['no_elements_selected']; ?>";
var L__ENTER_NAME = "<?php echo LANG['enter_name']; ?>";
var L__ENTER_NEW_HOSTNAME = "<?php echo LANG['enter_new_hostname']; ?>";
var L__CONFIRM_UNINSTALL_PACKAGE = "<?php echo LANG['confirm_uninstall_package']; ?>";
var L__CONFIRM_REMOVE_PACKAGE_ASSIGNMENT = "<?php echo LANG['confirm_remove_package_assignment']; ?>";
var L__CONFIRM_DELETE = "<?php echo LANG['confirm_delete']; ?>";
var L__CONFIRM_DELETE_PACKAGE = "<?php echo LANG['confirm_delete_package']; ?>";
var L__CONFIRM_DELETE_GROUP = "<?php echo LANG['confirm_delete_group']; ?>";
var L__CONFIRM_DELETE_JOB = "<?php echo LANG['confirm_delete_job']; ?>";
var L__CONFIRM_DELETE_JOBCONTAINER = "<?php echo LANG['confirm_delete_jobcontainer']; ?>";
var L__COMPUTER_ADDED = "<?php echo LANG['computer_added']; ?>";
var L__PACKAGES_ADDED = "<?php echo LANG['packages_added']; ?>";
var L__SEARCH_PLACEHOLDER = "<?php echo LANG['search_placeholder']; ?>";
var L__SAVED = "<?php echo LANG['saved']; ?>";
var L__OBJECT_RENAMED = "<?php echo LANG['object_renamed']; ?>";
var L__GROUP_RENAMED = "<?php echo LANG['group_renamed']; ?>";
var L__WOL_SENT = "<?php echo LANG['wol_packet_sent']; ?>";
var L__ERROR = "<?php echo LANG['error']; ?>";
var L__PASSWORDS_DO_NOT_MATCH = "<?php echo LANG['passwords_do_not_match']; ?>";
var L__NO_CONNECTION_TO_SERVER = "<?php echo LANG['no_connection_to_server']; ?>";
var L__PLEASE_CHECK_NETWORK = "<?php echo LANG['please_check_network']; ?>";
var L__PLEASE_CHECK_NETWORK = "<?php echo LANG['please_check_network']; ?>";
var L__IN_PROGRESS = "<?php echo LANG['in_progress']; ?>";
var L__CONFIRM_RENEW_JOBS = "<?php echo LANG['confirm_renew_jobs']; ?>";
var L__CONFIRM_CREATE_EMPTY_PACKAGE = "<?php echo LANG['confirm_create_empty_package']; ?>";
var L__ENTER_NEW_VALUE = "<?php echo LANG['enter_new_value']; ?>";
var L__ENTER_START_TIME = "<?php echo LANG['enter_start_time']; ?>";
var L__ENTER_NEW_PROCEDURE_POST_ACTION = "<?php echo LANG['enter_new_procedure_post_action']; ?>";
var L__ENTER_NEW_DOWNLOAD_FOR_UNINSTALL_VALUE = "<?php echo LANG['enter_new_download_for_uninstall_action']; ?>";
var L__ENTER_QUERY = "<?php echo LANG['enter_query']; ?>";
var L__FILE_TOO_BIG = "<?php echo LANG['file_too_big']; ?>";
var L__CHANGE_ICON = "<?php echo LANG['change_icon']; ?>";
var L__REMOVE_ICON = "<?php echo LANG['remove_icon']; ?>";
var L__ARE_YOU_SURE = "<?php echo LANG['are_you_sure']; ?>";
var L__ENTER_NEW_SEQUENCE_NUMBER = "<?php echo LANG['enter_new_sequence_number']; ?>";
var L__OBJECT_DELETED = "<?php echo LANG['object_deleted']; ?>";
var L__GROUP_DELETED = "<?php echo LANG['group_deleted']; ?>";
var L__OBJECT_REMOVED_FROM_GROUP = "<?php echo LANG['object_removed_from_group']; ?>";
var L__CREATE_SYSTEM_USER = "<?php echo LANG['create_system_user']; ?>";
var L__PASSWORDS_DO_NOT_MATCH = "<?php echo LANG['passwords_do_not_match']; ?>";
var L__NEW_PASSWORD = "<?php echo LANG['new_password']; ?>";
var L__WELCOME_TEXT = "<?php echo LANG['welcome_text']; ?>";
var L__WELCOME_DESCRIPTION = "<?php echo LANG['welcome_description']; ?>";

var L__DESKTOP_NOTIFICATIONS_NOT_SUPPORTED = "<?php echo LANG['desktop_notifications_not_supported']; ?>";
var L__DESKTOP_NOTIFICATIONS_DENIED = "<?php echo LANG['desktop_notifications_denied']; ?>";
var L__DESKTOP_NOTIFICATIONS_ALREADY_PERMITTED = "<?php echo LANG['desktop_notifications_already_permitted']; ?>";
var L__JOB_CONTAINER_STATUS_CHANGED = "<?php echo LANG['job_container_status_changed']; ?>";
